#
# Suit deploy test...-.
#
name: deploy on dev
on:
  pull_request:
    types: [closed]
    branches: [dev]
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: test step
        run: echo "Hello World!"
