# 
# Suit deploy test
# 
name: deploy on dev
on:
  pull_request_review:
    types:
      - submitted
    branches:
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: test step
        run: echo "Hello World!"
